package tp3;

import java.util.*; 
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 11518681
 */
public class telaDoTp3 extends javax.swing.JFrame {
    
    private ArrayList <reporter> ReporteresNaoAssociados = new ArrayList<>();
    
    private ArrayList <reporter> ReporteresAssociados = new ArrayList <>();
    Iterator<reporter> ra = ReporteresAssociados.iterator();
    
    private ArrayList <programa> ProgramasCadastrados = new ArrayList <>();
    
    private emissora brhue = new emissora(1 , "Br Organizações Huehuehue S/A");
    
    
    
    public telaDoTp3() {
        initComponents();
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        cadastrarPrograma = new javax.swing.JMenuItem();
        listarProgramas = new javax.swing.JMenuItem();
        listarProgramasPorReporter = new javax.swing.JMenuItem();
        removerPrograma = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        cadastrarReporter = new javax.swing.JMenuItem();
        associarReporter = new javax.swing.JMenuItem();
        listarReporteres = new javax.swing.JMenuItem();
        removerReporter = new javax.swing.JMenuItem();
        sobreOprograma = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        autor = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BR Organizações Huehuehue S/A");
        setIconImages(null);

        jLabel3.setBackground(new java.awt.Color(204, 0, 204));
        jLabel3.setFont(new java.awt.Font("Vladimir Script", 3, 36)); // NOI18N
        jLabel3.setText("\"BR Organizações Huehuehue S/A\"");

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 102));
        jMenuBar1.setForeground(new java.awt.Color(0, 153, 153));

        jMenu2.setText("Programa");

        cadastrarPrograma.setText("Cadastrar Programa");
        cadastrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProgramaActionPerformed(evt);
            }
        });
        jMenu2.add(cadastrarPrograma);

        listarProgramas.setText("Lista de Programas");
        listarProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProgramasActionPerformed(evt);
            }
        });
        jMenu2.add(listarProgramas);

        listarProgramasPorReporter.setText("Listar Programas por Repórteres");
        listarProgramasPorReporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProgramasPorReporterActionPerformed(evt);
            }
        });
        jMenu2.add(listarProgramasPorReporter);

        removerPrograma.setText("Remover Programa");
        removerPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProgramaActionPerformed(evt);
            }
        });
        jMenu2.add(removerPrograma);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Repórteres");

        cadastrarReporter.setText("Cadastrar Repórter");
        cadastrarReporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarReporterActionPerformed(evt);
            }
        });
        jMenu7.add(cadastrarReporter);

        associarReporter.setText("Associar Repórter");
        associarReporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associarReporterActionPerformed(evt);
            }
        });
        jMenu7.add(associarReporter);

        listarReporteres.setText("Listar Repórteres Associados");
        listarReporteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarReporteresActionPerformed(evt);
            }
        });
        jMenu7.add(listarReporteres);

        removerReporter.setText("Remover Repórter");
        removerReporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerReporterActionPerformed(evt);
            }
        });
        jMenu7.add(removerReporter);

        jMenuBar1.add(jMenu7);

        sobreOprograma.setText("Sobre");

        jMenuItem3.setText("Sobre o programa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        sobreOprograma.add(jMenuItem3);

        autor.setText("Autor");
        sobreOprograma.add(autor);

        jMenuBar1.add(sobreOprograma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cadastrarReporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarReporterActionPerformed
   
        cadastrarReporter cr = new cadastrarReporter(ReporteresNaoAssociados);
        cr.setVisible(true);
        
    }//GEN-LAST:event_cadastrarReporterActionPerformed

    private void cadastrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProgramaActionPerformed
       
        cadastrarprograma cp = new cadastrarprograma(ProgramasCadastrados, ReporteresAssociados);
        cp.setVisible(true);
        
    }//GEN-LAST:event_cadastrarProgramaActionPerformed

    private void listarProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProgramasActionPerformed
        
       Iterator <programa> pc = ProgramasCadastrados.iterator();
        
       while(pc.hasNext()){
          JOptionPane.showMessageDialog(null, pc.next().imprimeprog());
       }
        
    }//GEN-LAST:event_listarProgramasActionPerformed

    private void associarReporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associarReporterActionPerformed
        
        associarReporter ar = new associarReporter(ReporteresNaoAssociados, ReporteresAssociados);
        ar.setVisible(true);
        
    }//GEN-LAST:event_associarReporterActionPerformed

    private void listarReporteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarReporteresActionPerformed
        while(ra.hasNext()){
            JOptionPane.showMessageDialog(null, ra.next().imprimeRep());
        }
    }//GEN-LAST:event_listarReporteresActionPerformed

    private void listarProgramasPorReporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProgramasPorReporterActionPerformed
        listarProgramasPorReporter lpr = new listarProgramasPorReporter(ReporteresAssociados, ProgramasCadastrados);
        lpr.setVisible(true);
    }//GEN-LAST:event_listarProgramasPorReporterActionPerformed

    private void removerProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProgramaActionPerformed
        
        removerPrograma rp = new removerPrograma(ProgramasCadastrados);
        rp.setVisible(true);
        
    }//GEN-LAST:event_removerProgramaActionPerformed

    private void removerReporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerReporterActionPerformed
        
        removerReporter rr = new removerReporter(ReporteresAssociados);
        rr.setVisible(true);
        
    }//GEN-LAST:event_removerReporterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDoTp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDoTp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDoTp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDoTp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDoTp3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem associarReporter;
    private javax.swing.JMenuItem autor;
    private javax.swing.JMenuItem cadastrarPrograma;
    private javax.swing.JMenuItem cadastrarReporter;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem listarProgramas;
    private javax.swing.JMenuItem listarProgramasPorReporter;
    private javax.swing.JMenuItem listarReporteres;
    private javax.swing.JMenuItem removerPrograma;
    private javax.swing.JMenuItem removerReporter;
    private javax.swing.JMenu sobreOprograma;
    // End of variables declaration//GEN-END:variables
}
